name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: 'v'
          skip-tag: 'true'
          skip-commit:  'false'
          rc-wording:     'RELEASE,alpha'
          minor-wording:  'add,Adds,new'
          major-wording:  'MAJOR,cut-major'
          patch-wording:  'patch,fixes'
          commit-message: 'update version {{version}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_FILENAME: 'composer.json'
